=== Azure/autorest/packages/libs/autorest-schemas/example-schema.json
{
  "title": "A JSON Schema for x-ms-examples extension in Swagger 2.0 API.",
  "$id": "https://raw.githubusercontent.com/Azure/autorest/main/packages/libs/autorest-schemas/example-schema.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["parameters", "responses"],
  "description": "Describes the format of an example defined using the x-ms-examples extension.",
  "additionalProperties": false,
  "properties": {
    "operationId": {
      "description": "The operationId in the swagger specification for which the example is being provided.",
      "type": "string"
    },
    "title": {
      "description": "The title in the swagger spec that uniquely identifies the swagger spec.",
      "type": "string"
    },
    "description": {
      "description": "A brief explanation about the current scenario.",
      "type": "string"
    },
    "parameters": {
      "$ref": "#/xmsParametersExample"
    },
    "responses": {
      "type": "object",
      "description": "A dictionary of {possible HTTP status codes (as the dictionary key)} that can be received from that operation and {examples (as the dictionary value)} of response {body} and {headers (for long running operations)}.",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^([0-9]{3})$|^(default)$": {
          "$ref": "#/xmsResponseExample"
        }
      }
    },
    "x-ms-original-file": {
      "type": "string",
      "description": "INTERNAL: Value added coresponding to the uri of the examples when loaded via $ref"
    }
  },
  "xmsParametersExample": {
    "type": "object",
    "description": "A dictionary of parameter names and their sample values for a particular operation. Commonly used parameters in Azure, like 'api-version', 'subscriptionId' and 'resourceGroupName' have been defined as optional properties for ease of use. Please add other parameters as applicable in your example.",
    "additionalProperties": true,
    "properties": {
      "api-version": {
        "type": "string",
        "description": "An example of the api-version used in the request.",
        "minLength": 1
      },
      "subcriptionId": {
        "type": "string",
        "description": "An example of the subcriptionId used in the request.",
        "minLength": 1
      },
      "resourceGroupName": {
        "type": "string",
        "description": "An example of the resourceGroupName used in the request.",
        "pattern": "^[-\\w\\._\\(\\)]+$",
        "minLength": 1,
        "maxLength": 90
      }
    }
  },
  "xmsResponseHeaderExample": {
    "type": "object",
    "description": "Examples of response headers. Common response headers like 'location', 'azure-asyncoperation', 'retry-after', etc. are defined as optional properties for ease of use. Please feel free to add other response headers as applicable in the example.",
    "properties": {
      "location": {
        "type": "string",
        "description": "An example of the location header sent by the server, if applicable in the example.",
        "minLength": 10,
        "pattern": "^(http|https)://.*"
      },
      "azure-asyncoperation": {
        "type": "string",
        "description": "An example of the azure-asyncoperation header sent by the server, if applicable in the example.",
        "minLength": 10,
        "pattern": "^(http|https)://.*"
      },
      "retry-after": {
        "type": "string",
        "description": "An example value of the retry-after header sent by the server, if applicable in the example.",
        "minLength": 1
      }
    },
    "additionalProperties": true
  },
  "xmsResponseExample": {
    "type": "object",
    "description": "Describes headers and body of an example HTTP response, in the context of the x-ms-examples extension.",
    "properties": {
      "headers": {
        "$ref": "#/xmsResponseHeaderExample"
      },
      "body": {
        "type": ["object", "number", "array", "integer", "string", "boolean", "null"],
        "description": "Example of the response body if applicable for the operation. Don't specify the body if the server is not sending a response body. The outcome from `JSON.parse()`, needs to be described over here."
      }
    }
  }
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/imageExamples/Image_CreateFromASnapshotWithDiskEncryptionSet.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "imageName": "myImage",
    "parameters": {
      "location": "West US",
      "properties": {
        "storageProfile": {
          "osDisk": {
            "diskEncryptionSet": {
              "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/diskEncryptionSets/{existing-diskEncryptionSet-name}"
            },
            "managedDisk": {
              "id": "subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/myManagedDisk"
            },
            "osState": "Generalized",
            "osType": "Linux"
          }
        }
      }
    },
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscription-id}"
  },
  "responses": {
    "200": {
      "body": {
        "name": "myImage",
        "type": "Microsoft.Compute/images",
        "id": "/subscriptions/{subscription-id}/resourceGroups/disk/providers/Microsoft.Compute/images/myImage",
        "location": "westus",
        "properties": {
          "provisioningState": "Creating",
          "storageProfile": {
            "dataDisks": [],
            "osDisk": {
              "caching": "ReadWrite",
              "diskEncryptionSet": {
                "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/diskEncryptionSets/{existing-diskEncryptionSet-name}"
              },
              "managedDisk": {
                "id": "subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/myManagedDisk"
              },
              "osState": "Generalized",
              "osType": "Linux"
            }
          }
        }
      }
    },
    "201": {
      "body": {
        "name": "myImage",
        "type": "Microsoft.Compute/images",
        "id": "/subscriptions/{subscription-id}/resourceGroups/disk/providers/Microsoft.Compute/images/myImage",
        "location": "westus",
        "properties": {
          "provisioningState": "Creating",
          "storageProfile": {
            "dataDisks": [],
            "osDisk": {
              "caching": "ReadWrite",
              "diskEncryptionSet": {
                "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/diskEncryptionSets/{existing-diskEncryptionSet-name}"
              },
              "managedDisk": {
                "id": "subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/myManagedDisk"
              },
              "osState": "Generalized",
              "osType": "Linux"
            }
          }
        }
      }
    }
  },
  "operationId": "Images_CreateOrUpdate",
  "title": "Create a virtual machine image from a snapshot with DiskEncryptionSet resource."
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/Disks_GrantAccess_GetSasOnManagedDiskAndVmGuestState.json
{
  "parameters": {
    "api-version": "2023-04-02",
    "diskName": "myDisk",
    "grantAccessData": {
      "access": "Read",
      "durationInSeconds": 300,
      "getSecureVMGuestStateSAS": true
    },
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscription-id}"
  },
  "responses": {
    "200": {
      "body": {
        "accessSAS": "https://md-gpvmcxzlzxgd.partition.blob.storage.azure.net/xx3cqcx53f0v/abcd?sv=2014-02-14&sr=b&sk=key1&sig=XXX&st=2021-05-24T18:02:34Z&se=2021-05-24T18:19:14Z&sp=r",
        "securityDataAccessSAS": "https://md-gpvmcxzlzxgd.partition.blob.storage.azure.net/xx3cqcx53f0v/b9bf5824-6122-49e0-ba22-042f76ccd8a1_vmgs?sv=2014-02-14&sr=b&sk=key1&sig=XXX&st=2021-05-24T18:02:34Z&se=2021-05-24T18:19:14Z&sp=r"
      }
    },
    "202": {
      "headers": {
        "Location": "https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/operations/{operationId}&monitor=true&api-version=2023-04-02"
      }
    }
  },
  "operationId": "Disks_GrantAccess",
  "title": "Get sas on managed disk and VM guest state"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-dns/tsp-output/examples/2018-05-01/RecordSets_ListByType_ListCaaRecordsets.json
{
  "parameters": {
    "api-version": "2018-05-01",
    "recordType": "CAA",
    "resourceGroupName": "rg1",
    "subscriptionId": "subid",
    "zoneName": "zone1"
  },
  "responses": {
    "200": {
      "body": {
        "nextLink": "https://servicehost/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/dnsZones/zone1/CAA?api-version=2018-05-01&$skipToken=skipToken",
        "value": [
          {
            "name": "record1",
            "type": "Microsoft.Network/dnsZones/CAA",
            "etag": "00000000-0000-0000-0000-000000000000",
            "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/dnsZones/zone1/CAA/record1",
            "properties": {
              "TTL": 3600,
              "caaRecords": [
                {
                  "flags": 0,
                  "tag": "issue",
                  "value": "ca.contoso.com"
                }
              ],
              "fqdn": "record1.zone1",
              "metadata": {
                "key1": "value1"
              }
            }
          }
        ]
      }
    }
  },
  "operationId": "RecordSets_ListByType",
  "title": "List CAA recordsets"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/VirtualMachineScaleSets_CreateOrUpdate_CreateAScaleSetWithTerminateScheduledEventsEnabled.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "parameters": {
      "location": "westus",
      "properties": {
        "overprovision": true,
        "upgradePolicy": {
          "mode": "Manual"
        },
        "virtualMachineProfile": {
          "networkProfile": {
            "networkInterfaceConfigurations": [
              {
                "name": "{vmss-name}",
                "properties": {
                  "enableIPForwarding": true,
                  "ipConfigurations": [
                    {
                      "name": "{vmss-name}",
                      "properties": {
                        "subnet": {
                          "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/{existing-virtual-network-name}/subnets/{existing-subnet-name}"
                        }
                      }
                    }
                  ],
                  "primary": true
                }
              }
            ]
          },
          "osProfile": {
            "adminPassword": "{your-password}",
            "adminUsername": "{your-username}",
            "computerNamePrefix": "{vmss-name}"
          },
          "scheduledEventsProfile": {
            "terminateNotificationProfile": {
              "enable": true,
              "notBeforeTimeout": "PT5M"
            }
          },
          "storageProfile": {
            "imageReference": {
              "offer": "WindowsServer",
              "publisher": "MicrosoftWindowsServer",
              "sku": "2016-Datacenter",
              "version": "latest"
            },
            "osDisk": {
              "caching": "ReadWrite",
              "createOption": "FromImage",
              "managedDisk": {
                "storageAccountType": "Standard_LRS"
              }
            }
          }
        }
      },
      "sku": {
        "name": "Standard_D1_v2",
        "capacity": 3,
        "tier": "Standard"
      }
    },
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscription-id}",
    "vmScaleSetName": "{vmss-name}"
  },
  "responses": {
    "200": {
      "body": {
        "name": "{vmss-name}",
        "type": "Microsoft.Compute/virtualMachineScaleSets",
        "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachineScaleSets/{vmss-name}",
        "location": "westus",
        "properties": {
          "overprovision": true,
          "provisioningState": "Creating",
          "singlePlacementGroup": true,
          "uniqueId": "d053ec5a-8da6-495f-ab13-38216503c6d7",
          "upgradePolicy": {
            "mode": "Manual"
          },
          "virtualMachineProfile": {
            "networkProfile": {
              "networkInterfaceConfigurations": [
                {
                  "name": "{vmss-name}",
                  "properties": {
                    "dnsSettings": {
                      "dnsServers": []
                    },
                    "enableAcceleratedNetworking": false,
                    "enableIPForwarding": true,
                    "ipConfigurations": [
                      {
                        "name": "{vmss-name}",
                        "properties": {
                          "privateIPAddressVersion": "IPv4",
                          "subnet": {
                            "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/nsgExistingVnet/subnets/nsgExistingSubnet"
                          }
                        }
                      }
                    ],
                    "primary": true
                  }
                }
              ]
            },
            "osProfile": {
              "adminUsername": "{your-username}",
              "computerNamePrefix": "{vmss-name}",
              "secrets": [],
              "windowsConfiguration": {
                "enableAutomaticUpdates": true,
                "provisionVMAgent": true
              }
            },
            "scheduledEventsProfile": {
              "terminateNotificationProfile": {
                "enable": true,
                "notBeforeTimeout": "PT5M"
              }
            },
            "storageProfile": {
              "imageReference": {
                "offer": "WindowsServer",
                "publisher": "MicrosoftWindowsServer",
                "sku": "2016-Datacenter",
                "version": "latest"
              },
              "osDisk": {
                "caching": "ReadWrite",
                "createOption": "FromImage",
                "managedDisk": {
                  "storageAccountType": "Standard_LRS"
                }
              }
            }
          }
        },
        "sku": {
          "name": "Standard_D1_v2",
          "capacity": 3,
          "tier": "Standard"
        }
      }
    },
    "201": {
      "body": {
        "name": "{vmss-name}",
        "type": "Microsoft.Compute/virtualMachineScaleSets",
        "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachineScaleSets/{vmss-name}",
        "location": "westus",
        "properties": {
          "overprovision": true,
          "provisioningState": "Creating",
          "singlePlacementGroup": true,
          "uniqueId": "d053ec5a-8da6-495f-ab13-38216503c6d7",
          "upgradePolicy": {
            "mode": "Manual"
          },
          "virtualMachineProfile": {
            "networkProfile": {
              "networkInterfaceConfigurations": [
                {
                  "name": "{vmss-name}",
                  "properties": {
                    "dnsSettings": {
                      "dnsServers": []
                    },
                    "enableAcceleratedNetworking": false,
                    "enableIPForwarding": true,
                    "ipConfigurations": [
                      {
                        "name": "{vmss-name}",
                        "properties": {
                          "privateIPAddressVersion": "IPv4",
                          "subnet": {
                            "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Network/virtualNetworks/nsgExistingVnet/subnets/nsgExistingSubnet"
                          }
                        }
                      }
                    ],
                    "primary": true
                  }
                }
              ]
            },
            "osProfile": {
              "adminUsername": "{your-username}",
              "computerNamePrefix": "{vmss-name}",
              "secrets": [],
              "windowsConfiguration": {
                "enableAutomaticUpdates": true,
                "provisionVMAgent": true
              }
            },
            "scheduledEventsProfile": {
              "terminateNotificationProfile": {
                "enable": true,
                "notBeforeTimeout": "PT5M"
              }
            },
            "storageProfile": {
              "imageReference": {
                "offer": "WindowsServer",
                "publisher": "MicrosoftWindowsServer",
                "sku": "2016-Datacenter",
                "version": "latest"
              },
              "osDisk": {
                "caching": "ReadWrite",
                "createOption": "FromImage",
                "managedDisk": {
                  "storageAccountType": "Standard_LRS"
                }
              }
            }
          }
        },
        "sku": {
          "name": "Standard_D1_v2",
          "capacity": 3,
          "tier": "Standard"
        }
      }
    }
  },
  "operationId": "VirtualMachineScaleSets_CreateOrUpdate",
  "title": "Create a scale set with terminate scheduled events enabled."
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/keyvault/tsp-output/examples/7.4-preview.1/verify-example.json
{
  "parameters": {
    "api-version": "7.4-preview.1",
    "key-name": "testkey",
    "key-version": "9885aa558e8d448789683188f8c194b0",
    "parameters": {
      "alg": "RS512",
      "digest": "aKFG8NXcfTzqyR44rW42484K_zZI_T7zZuebvWuNgAoEI1gXYmxrshp42CunSmmu4oqo4-IrCikPkNIBkHXnAW2cv03Ad0UpwXhVfepK8zzDBaJPMKVGS-ZRz8CshEyGDKaLlb3J3zEkXpM3RrSEr0mdV6hndHD_mznLB5RmFui5DsKAhez4vUqajgtkgcPfCekMqeSwp6r9ItVL-gEoAohx8XMDsPedqu-7BuZcBcdayaPuBRL4wWoTDULA11P-UN_sJ5qMj3BbiRYhIlBWGR04wIGfZ3pkJjHJUpOvgH2QajdYPzUBauOCewMYbq9XkLRSzI_A7HkkDVycugSeAA",
      "value": "RUE3Nzg4NTQ4QjQ5RjFFN0U2NzAyQzhDNEMwMkJDOTA1MTYyOTUzNjI5NDhBNzZDQTlFOTM1NDA2M0ZGMjk2Mg"
    },
    "vaultBaseUrl": "https://myvault.vault.azure.net/"
  },
  "responses": {
    "200": {
      "body": {
        "value": true
      }
    }
  },
  "operationId": "verify",
  "title": "Verify"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/unknown/VirtualMachineScaleSets_SetOrchestrationServiceState_VirtualMachineScaleSetSetOrchestrationServiceStateMaximumSetGen.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "parameters": {
      "action": "Resume",
      "serviceName": "AutomaticRepairs"
    },
    "resourceGroupName": "rgcompute",
    "subscriptionId": "{subscription-id}",
    "vmScaleSetName": "aaaaaaaaaaaaaaaa"
  },
  "responses": {
    "200": {},
    "202": {
      "headers": {
        "location": "https://foo.com/operationstatus"
      }
    }
  },
  "operationId": "VirtualMachineScaleSets_SetOrchestrationServiceState",
  "title": "VirtualMachineScaleSet_SetOrchestrationServiceState_MaximumSet_Gen"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/analyzeText/tsp-output/examples/2022-05-01/analyzetext-authoring/SuccessfulTrainProject.json
{
  "parameters": {
    "Endpoint": "{Endpoint}",
    "Ocp-Apim-Subscription-Key": "{API key}",
    "api-version": "2022-05-01",
    "body": {
      "evaluationOptions": {
        "kind": "percentage",
        "testingSplitPercentage": 20,
        "trainingSplitPercentage": 80
      },
      "modelLabel": "model1",
      "trainingConfigVersion": "latest"
    },
    "projectName": "LoanAgreements"
  },
  "responses": {
    "202": {
      "headers": {
        "operation-location": "{Endpoint}/language/authoring/analyze-text/projects/LoanAgreements/train/jobs/4d37982f-fded-4c2c-afe3-15953b5919b6_637858368000000000?api-version=2022-05-01"
      }
    }
  },
  "operationId": "TextAnalysisAuthoring_Train",
  "title": "Successful Train Project"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-servicenetworking/swagger-output/examples/TrafficControllerPut.json
{
  "operationId": "TrafficControllerInterface_CreateOrUpdate",
  "parameters": {
    "api-version": "2023-11-01",
    "resource": {
      "location": "NorthCentralUS",
      "tags": {
        "key1": "value1"
      }
    },
    "resourceGroupName": "rg1",
    "subscriptionId": "subid",
    "trafficControllerName": "tc1"
  },
  "title": "Put Traffic Controller",
  "responses": {
    "200": {
      "body": {
        "name": "tc1",
        "type": "Microsoft.ServiceNetworking/trafficControllers",
        "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.ServiceNetworking/trafficControllers/tc1",
        "location": "NorthCentralUS",
        "properties": {
          "associations": [
            {
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.ServiceNetworking/trafficControllers/tc1/association/as1"
            }
          ],
          "configurationEndpoints": [
            "abc.trafficcontroller.azure.net"
          ],
          "frontends": [
            {
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.ServiceNetworking/trafficControllers/tc1/frontends/fe1"
            }
          ],
          "provisioningState": "Succeeded"
        },
        "tags": {
          "key1": "value1"
        }
      }
    },
    "201": {
      "body": {
        "name": "tc1",
        "type": "Microsoft.ServiceNetworking/trafficControllers",
        "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.ServiceNetworking/trafficControllers/tc1",
        "location": "NorthCentralUS",
        "properties": {
          "associations": [
            {
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.ServiceNetworking/trafficControllers/tc1/association/as1"
            }
          ],
          "configurationEndpoints": [
            "abc.trafficcontroller.azure.net"
          ],
          "frontends": [
            {
              "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.ServiceNetworking/trafficControllers/tc1/frontends/fe1"
            }
          ],
          "provisioningState": "Succeeded"
        },
        "tags": {
          "key1": "value1"
        }
      }
    }
  }
}
