=== Azure/autorest/packages/libs/autorest-schemas/example-schema.json
{
  "title": "A JSON Schema for x-ms-examples extension in Swagger 2.0 API.",
  "$id": "https://raw.githubusercontent.com/Azure/autorest/main/packages/libs/autorest-schemas/example-schema.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["parameters", "responses"],
  "description": "Describes the format of an example defined using the x-ms-examples extension.",
  "additionalProperties": false,
  "properties": {
    "operationId": {
      "description": "The operationId in the swagger specification for which the example is being provided.",
      "type": "string"
    },
    "title": {
      "description": "The title in the swagger spec that uniquely identifies the swagger spec.",
      "type": "string"
    },
    "description": {
      "description": "A brief explanation about the current scenario.",
      "type": "string"
    },
    "parameters": {
      "$ref": "#/xmsParametersExample"
    },
    "responses": {
      "type": "object",
      "description": "A dictionary of {possible HTTP status codes (as the dictionary key)} that can be received from that operation and {examples (as the dictionary value)} of response {body} and {headers (for long running operations)}.",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^([0-9]{3})$|^(default)$": {
          "$ref": "#/xmsResponseExample"
        }
      }
    },
    "x-ms-original-file": {
      "type": "string",
      "description": "INTERNAL: Value added coresponding to the uri of the examples when loaded via $ref"
    }
  },
  "xmsParametersExample": {
    "type": "object",
    "description": "A dictionary of parameter names and their sample values for a particular operation. Commonly used parameters in Azure, like 'api-version', 'subscriptionId' and 'resourceGroupName' have been defined as optional properties for ease of use. Please add other parameters as applicable in your example.",
    "additionalProperties": true,
    "properties": {
      "api-version": {
        "type": "string",
        "description": "An example of the api-version used in the request.",
        "minLength": 1
      },
      "subcriptionId": {
        "type": "string",
        "description": "An example of the subcriptionId used in the request.",
        "minLength": 1
      },
      "resourceGroupName": {
        "type": "string",
        "description": "An example of the resourceGroupName used in the request.",
        "pattern": "^[-\\w\\._\\(\\)]+$",
        "minLength": 1,
        "maxLength": 90
      }
    }
  },
  "xmsResponseHeaderExample": {
    "type": "object",
    "description": "Examples of response headers. Common response headers like 'location', 'azure-asyncoperation', 'retry-after', etc. are defined as optional properties for ease of use. Please feel free to add other response headers as applicable in the example.",
    "properties": {
      "location": {
        "type": "string",
        "description": "An example of the location header sent by the server, if applicable in the example.",
        "minLength": 10,
        "pattern": "^(http|https)://.*"
      },
      "azure-asyncoperation": {
        "type": "string",
        "description": "An example of the azure-asyncoperation header sent by the server, if applicable in the example.",
        "minLength": 10,
        "pattern": "^(http|https)://.*"
      },
      "retry-after": {
        "type": "string",
        "description": "An example value of the retry-after header sent by the server, if applicable in the example.",
        "minLength": 1
      }
    },
    "additionalProperties": true
  },
  "xmsResponseExample": {
    "type": "object",
    "description": "Describes headers and body of an example HTTP response, in the context of the x-ms-examples extension.",
    "properties": {
      "headers": {
        "$ref": "#/xmsResponseHeaderExample"
      },
      "body": {
        "type": ["object", "number", "array", "integer", "string", "boolean", "null"],
        "description": "Example of the response body if applicable for the operation. Don't specify the body if the server is not sending a response body. The outcome from `JSON.parse()`, needs to be described over here."
      }
    }
  }
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/Images_Delete_Image_Delete_Maximum_Set_Gen.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "imageName": "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "resourceGroupName": "rgcompute",
    "subscriptionId": "{subscription-id}"
  },
  "responses": {
    "200": {},
    "202": {
      "headers": {
        "location": "https://foo.com/operationstatus"
      }
    },
    "204": {}
  },
  "operationId": "Images_Delete",
  "title": "Image_Delete_MaximumSet_Gen"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/VirtualMachines_InstanceView_Get_Virtual_Machine_Instance_View.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscription-id}",
    "vmName": "myVM"
  },
  "responses": {
    "200": {
      "body": {
        "bootDiagnostics": {
          "consoleScreenshotBlobUri": "https://{myStorageAccount}.blob.core.windows.net/bootdiagnostics-myOsDisk/myOsDisk.screenshot.bmp",
          "serialConsoleLogBlobUri": "https://{myStorageAccount}.blob.core.windows.net/bootdiagnostics-myOsDisk/myOsDisk.serialconsole.log"
        },
        "computerName": "myVM",
        "disks": [
          {
            "name": "myOsDisk",
            "statuses": [
              {
                "code": "ProvisioningState/succeeded",
                "displayStatus": "Provisioning succeeded",
                "level": "Info",
                "time": "2019-10-14T21:29:47.477089+00:00"
              }
            ]
          },
          {
            "name": "myDataDisk0",
            "statuses": [
              {
                "code": "ProvisioningState/succeeded",
                "displayStatus": "Provisioning succeeded",
                "level": "Info",
                "time": "2019-10-14T21:29:47.461517+00:00"
              }
            ]
          }
        ],
        "hyperVGeneration": "V1",
        "osName": "Windows Server 2016 Datacenter",
        "osVersion": "Microsoft Windows NT 10.0.14393.0",
        "patchStatus": {
          "availablePatchSummary": {
            "assessmentActivityId": "68f8b292-dfc2-4646-9781-33cc88631968",
            "criticalAndSecurityPatchCount": 1,
            "error": null,
            "lastModifiedTime": "2020-04-24T21:02:04.2556154Z",
            "otherPatchCount": 2,
            "rebootPending": true,
            "startTime": "2020-04-24T21:02:04.2556154Z",
            "status": "Succeeded"
          },
          "configurationStatuses": [
            {
              "code": "PatchModeConfigurationState/Ready",
              "displayStatus": "Status_PatchModeConfigurationState_Ready",
              "level": "Info",
              "time": "2020-04-24T21:02:04.2556154Z"
            },
            {
              "code": "AssessmentModeConfigurationState/Pending",
              "displayStatus": "Status_AssessmentModeConfigurationState_Pending",
              "level": "Info",
              "time": "2020-04-24T21:02:04.2556154Z"
            }
          ],
          "lastPatchInstallationSummary": {
            "error": null,
            "excludedPatchCount": 1,
            "failedPatchCount": 1,
            "installationActivityId": "68f8b292-dfc2-4646-9981-33cc88631968",
            "installedPatchCount": 1,
            "lastModifiedTime": "2020-04-24T21:02:04.2556154Z",
            "maintenanceWindowExceeded": false,
            "notSelectedPatchCount": 1,
            "pendingPatchCount": 1,
            "startTime": "2020-04-24T21:02:04.2556154Z",
            "status": "Succeeded"
          }
        },
        "platformFaultDomain": 1,
        "platformUpdateDomain": 1,
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "displayStatus": "Provisioning succeeded",
            "level": "Info",
            "time": "2019-10-14T21:30:12.8051917+00:00"
          },
          {
            "code": "PowerState/running",
            "displayStatus": "VM running",
            "level": "Info"
          }
        ],
        "vmAgent": {
          "extensionHandlers": [
            {
              "type": "Microsoft.Azure.Security.IaaSAntimalware",
              "status": {
                "code": "ProvisioningState/succeeded",
                "displayStatus": "Ready",
                "level": "Info"
              },
              "typeHandlerVersion": "1.5.5.9"
            }
          ],
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "displayStatus": "Ready",
              "level": "Info",
              "message": "GuestAgent is running and accepting new configurations.",
              "time": "2019-10-14T23:11:22+00:00"
            }
          ],
          "vmAgentVersion": "2.7.41491.949"
        },
        "extensions": [
          {
            "name": "IaaSAntiMalware-ext0",
            "type": "Microsoft.Azure.Security.IaaSAntimalware",
            "statuses": [
              {
                "code": "ProvisioningState/succeeded",
                "displayStatus": "Provisioning succeeded",
                "level": "Info",
                "message": "Microsoft Antimalware enabled"
              }
            ],
            "typeHandlerVersion": "1.5.5.9"
          }
        ]
      }
    }
  },
  "operationId": "VirtualMachines_InstanceView",
  "title": "Get Virtual Machine Instance View."
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-dns/tsp-output/examples/2018-05-01/RecordSets_ListByType_ListCnameRecordsets.json
{
  "parameters": {
    "api-version": "2018-05-01",
    "recordType": "CNAME",
    "resourceGroupName": "rg1",
    "subscriptionId": "subid",
    "zoneName": "zone1"
  },
  "responses": {
    "200": {
      "body": {
        "nextLink": "https://servicehost/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/dnsZones/zone1/CNAME?api-version=2018-05-01&$skipToken=skipToken",
        "value": [
          {
            "name": "record1",
            "type": "Microsoft.Network/dnsZones/CNAME",
            "etag": "00000000-0000-0000-0000-000000000000",
            "id": "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/dnsZones/zone1/CNAME/record1",
            "properties": {
              "CNAMERecord": {
                "cname": "contoso.com"
              },
              "TTL": 3600,
              "fqdn": "record1.zone1",
              "metadata": {
                "key1": "value1"
              }
            }
          }
        ]
      }
    }
  },
  "operationId": "RecordSets_ListByType",
  "title": "List CNAME recordsets"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/Galleries_CreateOrUpdate_CreateOrUpdateASimpleGalleryWithSoftDeletionEnabled.json
{
  "parameters": {
    "api-version": "2022-03-03",
    "gallery": {
      "location": "West US",
      "properties": {
        "description": "This is the gallery description.",
        "softDeletePolicy": {
          "isSoftDeleteEnabled": true
        }
      }
    },
    "galleryName": "myGalleryName",
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscription-id}"
  },
  "responses": {
    "200": {
      "body": {
        "name": "myGalleryName",
        "location": "West US",
        "properties": {
          "description": "This is the gallery description.",
          "identifier": {
            "uniqueName": "{subscription-id}-MYGALLERYNAME"
          },
          "provisioningState": "Updating",
          "softDeletePolicy": {
            "isSoftDeleteEnabled": true
          }
        }
      }
    },
    "201": {
      "body": {
        "name": "myGalleryName",
        "location": "West US",
        "properties": {
          "description": "This is the gallery description.",
          "identifier": {
            "uniqueName": "{subscription-id}-MYGALLERYNAME"
          },
          "provisioningState": "Creating",
          "softDeletePolicy": {
            "isSoftDeleteEnabled": true
          }
        }
      }
    },
    "202": {
      "body": {
        "name": "myGalleryName",
        "location": "West US",
        "properties": {
          "description": "This is the gallery description.",
          "identifier": {
            "uniqueName": "{subscription-id}-MYGALLERYNAME"
          },
          "provisioningState": "Updating",
          "softDeletePolicy": {
            "isSoftDeleteEnabled": true
          }
        }
      }
    }
  },
  "operationId": "Galleries_CreateOrUpdate",
  "title": "Create or update a simple gallery with soft deletion enabled."
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/VirtualMachineScaleSets_Redeploy_Virtual_Machine_Scale_Set_Redeploy_Maximum_Set_Gen.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "resourceGroupName": "rgcompute",
    "subscriptionId": "{subscription-id}",
    "vmInstanceIDs": {
      "instanceIds": [
        "aaaaaaaaaaaaaaaaa"
      ]
    },
    "vmScaleSetName": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "responses": {
    "200": {},
    "202": {
      "headers": {
        "location": "https://foo.com/operationstatus"
      }
    }
  },
  "operationId": "VirtualMachineScaleSets_Redeploy",
  "title": "VirtualMachineScaleSet_Redeploy_MaximumSet_Gen"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/VirtualMachineExtensions_Get_Virtual_Machine_Extension_Get_Maximum_Set_Gen.json
{
  "parameters": {
    "$expand": "aaaaaa",
    "api-version": "2023-07-01",
    "resourceGroupName": "rgcompute",
    "subscriptionId": "{subscription-id}",
    "vmExtensionName": "aaaaaaa",
    "vmName": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "responses": {
    "200": {
      "body": {
        "name": "myVMExtension",
        "type": "Microsoft.Compute/virtualMachines/extensions",
        "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM/extensions/myVMExtension",
        "location": "westus",
        "properties": {
          "type": "extType",
          "autoUpgradeMinorVersion": true,
          "enableAutomaticUpgrade": true,
          "forceUpdateTag": "a",
          "instanceView": {
            "name": "aaaaaaaaaaaaaaaaa",
            "type": "aaaaaaaaa",
            "statuses": [
              {
                "code": "aaaaaaaaaaaaaaaaaaaaaaa",
                "displayStatus": "aaaaaa",
                "level": "Info",
                "message": "a",
                "time": "2021-11-30T12:58:26.522Z"
              }
            ],
            "substatuses": [
              {
                "code": "aaaaaaaaaaaaaaaaaaaaaaa",
                "displayStatus": "aaaaaa",
                "level": "Info",
                "message": "a",
                "time": "2021-11-30T12:58:26.522Z"
              }
            ],
            "typeHandlerVersion": "aaaaaaaaaaaaaaaaaaaaaaaaaa"
          },
          "protectedSettings": {},
          "provisioningState": "Creating",
          "publisher": "extPublisher",
          "settings": {},
          "suppressFailures": true,
          "typeHandlerVersion": "1.2"
        },
        "tags": {
          "key9183": "aa"
        }
      }
    }
  },
  "operationId": "VirtualMachineExtensions_Get",
  "title": "VirtualMachineExtension_Get_MaximumSet_Gen"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/RestorePointCollections_ListAll.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "subscriptionId": "{subscription-id}"
  },
  "responses": {
    "200": {
      "body": {
        "value": [
          {
            "name": "restorePointCollection1",
            "type": "Microsoft.Compute/restorePointCollections",
            "id": "/subscriptions/{subscription-id}/resourceGroups/resourceGroup1/providers/Microsoft.Compute/restorePointCollections/restorePointCollection1",
            "location": "westus",
            "properties": {
              "provisioningState": "Succeeded",
              "restorePointCollectionId": "59f04a5d-f783-4200-a1bd-d3f464e8c4b4",
              "source": {
                "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/VM_Test",
                "location": "westus"
              }
            },
            "tags": {
              "myTag1": "tagValue1"
            }
          },
          {
            "name": "restorePointCollection2",
            "type": "Microsoft.Compute/restorePointCollections",
            "id": "/subscriptions/{subscription-id}/resourceGroups/resourceGroup2/providers/Microsoft.Compute/restorePointCollections/restorePointCollection2",
            "location": "westus",
            "properties": {
              "provisioningState": "Deleting",
              "restorePointCollectionId": "2875c590-e337-4102-9668-4f5b7e3f98a4",
              "source": {
                "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/VM_Prod",
                "location": "westus"
              }
            },
            "tags": {
              "myTag1": "tagValue1"
            }
          }
        ]
      }
    }
  },
  "operationId": "RestorePointCollections_ListAll",
  "title": "Gets the list of restore point collections in a subscription"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/imageExamples/Image_ListByResourceGroup.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscription-id}"
  },
  "responses": {
    "200": {
      "body": {
        "nextLink": "http://svchost:99/subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/images?$skiptoken={token}/Subscriptions/{subscriptionId}/ResourceGroups/myResourceGroup/UserVMImages/myImageName",
        "value": [
          {
            "name": "myImage",
            "type": "Microsoft.Compute/images",
            "id": "/subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/images/myImage",
            "location": "West US",
            "properties": {
              "provisioningState": "created",
              "storageProfile": {
                "dataDisks": [
                  {
                    "blobUri": "https://mystorageaccount.blob.core.windows.net/dataimages/dataimage.vhd",
                    "lun": 1,
                    "managedDisk": {
                      "id": "subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/myManagedDisk2"
                    },
                    "snapshot": {
                      "id": "subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/snapshots/mySnapshot2"
                    },
                    "storageAccountType": "Standard_LRS"
                  }
                ],
                "osDisk": {
                  "blobUri": "https://mystorageaccount.blob.core.windows.net/osimages/osimage.vhd",
                  "managedDisk": {
                    "id": "subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/myManagedDisk1"
                  },
                  "osState": "Generalized",
                  "osType": "Windows",
                  "snapshot": {
                    "id": "subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/snapshots/mySnapshot1"
                  },
                  "storageAccountType": "Standard_LRS"
                }
              }
            }
          }
        ]
      }
    }
  },
  "operationId": "Images_ListByResourceGroup",
  "title": "List all virtual machine images in a resource group."
}
