=== Azure/autorest/packages/libs/autorest-schemas/example-schema.json
{
  "title": "A JSON Schema for x-ms-examples extension in Swagger 2.0 API.",
  "$id": "https://raw.githubusercontent.com/Azure/autorest/main/packages/libs/autorest-schemas/example-schema.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["parameters", "responses"],
  "description": "Describes the format of an example defined using the x-ms-examples extension.",
  "additionalProperties": false,
  "properties": {
    "operationId": {
      "description": "The operationId in the swagger specification for which the example is being provided.",
      "type": "string"
    },
    "title": {
      "description": "The title in the swagger spec that uniquely identifies the swagger spec.",
      "type": "string"
    },
    "description": {
      "description": "A brief explanation about the current scenario.",
      "type": "string"
    },
    "parameters": {
      "$ref": "#/xmsParametersExample"
    },
    "responses": {
      "type": "object",
      "description": "A dictionary of {possible HTTP status codes (as the dictionary key)} that can be received from that operation and {examples (as the dictionary value)} of response {body} and {headers (for long running operations)}.",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^([0-9]{3})$|^(default)$": {
          "$ref": "#/xmsResponseExample"
        }
      }
    },
    "x-ms-original-file": {
      "type": "string",
      "description": "INTERNAL: Value added coresponding to the uri of the examples when loaded via $ref"
    }
  },
  "xmsParametersExample": {
    "type": "object",
    "description": "A dictionary of parameter names and their sample values for a particular operation. Commonly used parameters in Azure, like 'api-version', 'subscriptionId' and 'resourceGroupName' have been defined as optional properties for ease of use. Please add other parameters as applicable in your example.",
    "additionalProperties": true,
    "properties": {
      "api-version": {
        "type": "string",
        "description": "An example of the api-version used in the request.",
        "minLength": 1
      },
      "subcriptionId": {
        "type": "string",
        "description": "An example of the subcriptionId used in the request.",
        "minLength": 1
      },
      "resourceGroupName": {
        "type": "string",
        "description": "An example of the resourceGroupName used in the request.",
        "pattern": "^[-\\w\\._\\(\\)]+$",
        "minLength": 1,
        "maxLength": 90
      }
    }
  },
  "xmsResponseHeaderExample": {
    "type": "object",
    "description": "Examples of response headers. Common response headers like 'location', 'azure-asyncoperation', 'retry-after', etc. are defined as optional properties for ease of use. Please feel free to add other response headers as applicable in the example.",
    "properties": {
      "location": {
        "type": "string",
        "description": "An example of the location header sent by the server, if applicable in the example.",
        "minLength": 10,
        "pattern": "^(http|https)://.*"
      },
      "azure-asyncoperation": {
        "type": "string",
        "description": "An example of the azure-asyncoperation header sent by the server, if applicable in the example.",
        "minLength": 10,
        "pattern": "^(http|https)://.*"
      },
      "retry-after": {
        "type": "string",
        "description": "An example value of the retry-after header sent by the server, if applicable in the example.",
        "minLength": 1
      }
    },
    "additionalProperties": true
  },
  "xmsResponseExample": {
    "type": "object",
    "description": "Describes headers and body of an example HTTP response, in the context of the x-ms-examples extension.",
    "properties": {
      "headers": {
        "$ref": "#/xmsResponseHeaderExample"
      },
      "body": {
        "type": ["object", "number", "array", "integer", "string", "boolean", "null"],
        "description": "Example of the response body if applicable for the operation. Don't specify the body if the server is not sending a response body. The outcome from `JSON.parse()`, needs to be described over here."
      }
    }
  }
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/VirtualMachineExtensions_Delete_VirtualMachineExtensionDeleteMinimumSetGen.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "resourceGroupName": "rgcompute",
    "subscriptionId": "{subscription-id}",
    "vmExtensionName": "aa",
    "vmName": "aaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "responses": {
    "200": {},
    "202": {
      "headers": {
        "location": "https://foo.com/operationstatus"
      }
    },
    "204": {}
  },
  "operationId": "VirtualMachineExtensions_Delete",
  "title": "VirtualMachineExtension_Delete_MinimumSet_Gen"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/capacityReservationExamples/CapacityReservationGroup_Get.json
{
  "parameters": {
    "$expand": "instanceView",
    "api-version": "2023-07-01",
    "capacityReservationGroupName": "myCapacityReservationGroup",
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscriptionId}"
  },
  "responses": {
    "200": {
      "body": {
        "name": "myCapacityReservationGroup",
        "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/CapacityReservationGroups/myCapacityReservationGroup",
        "location": "westus",
        "properties": {
          "capacityReservations": [
            {
              "id": "subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/capacityReservationGroups/myCapacityReservationGroup/capacityReservations/myCapacityReservation1"
            },
            {
              "id": "subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/capacityReservationGroups/myCapacityReservationGroup/capacityReservations/myCapacityReservation2"
            }
          ],
          "instanceView": {
            "capacityReservations": [
              {
                "name": "myCapacityReservation1",
                "statuses": [
                  {
                    "code": "ProvisioningState/succeeded",
                    "displayStatus": "Provisioning succeeded",
                    "level": "Info"
                  }
                ],
                "utilizationInfo": {
                  "currentCapacity": 5,
                  "virtualMachinesAllocated": [
                    {
                      "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM1"
                    },
                    {
                      "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM2"
                    }
                  ]
                }
              },
              {
                "name": "myCapacityReservation2",
                "statuses": [
                  {
                    "code": "ProvisioningState/succeeded",
                    "displayStatus": "Provisioning succeeded",
                    "level": "Info"
                  }
                ],
                "utilizationInfo": {
                  "currentCapacity": 5,
                  "virtualMachinesAllocated": [
                    {
                      "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM3"
                    },
                    {
                      "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM4"
                    }
                  ]
                }
              }
            ]
          }
        },
        "tags": {
          "{tagName}": "{tagValue}"
        },
        "zones": [
          "3",
          "1"
        ]
      }
    }
  },
  "operationId": "CapacityReservationGroups_Get",
  "title": "Get a capacity reservation Group."
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/SharedGalleryImageVersions_List.json
{
  "parameters": {
    "api-version": "2022-03-03",
    "galleryImageName": "myGalleryImageName",
    "galleryUniqueName": "galleryUniqueName",
    "location": "myLocation",
    "subscriptionId": "{subscription-id}"
  },
  "responses": {
    "200": {
      "body": {
        "nextLink": "http://svchost:99/subscriptions/{subscription-Id}/providers/Microsoft.Compute/sharedGalleries/galleryUniqueName/images/myGalleryImageName/versions?$skiptoken={token}/Subscriptions/{subscription-Id}/galleries/galleryUniqueName/images/myGalleryImageName/versions/myGalleryImageVersionName",
        "value": [
          {
            "name": "myGalleryImageVersionName",
            "identifier": {
              "uniqueId": "/SharedGalleries/galleryUniqueName/Images/myGalleryImageName/Versions/myGalleryImageVersionName"
            },
            "location": "myLocation",
            "properties": {
              "endOfLifeDate": "2022-03-20T09:12:28Z",
              "excludeFromLatest": false,
              "publishedDate": "2018-03-20T09:12:28Z",
              "storageProfile": {
                "osDiskImage": {
                  "diskSizeGB": 29,
                  "hostCaching": "None"
                }
              }
            }
          }
        ]
      }
    }
  },
  "operationId": "SharedGalleryImageVersions_List",
  "title": "List shared gallery image versions."
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/Galleries_ListByResourceGroup.json
{
  "parameters": {
    "api-version": "2022-03-03",
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscription-id}"
  },
  "responses": {
    "200": {
      "body": {
        "nextLink": "http://svchost:99/subscriptions/{subscriptionId}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/galleries?$skiptoken={token}/Subscriptions/{subscriptionId}/ResourceGroups/myResourceGroup/galleries/myGalleryName",
        "value": [
          {
            "name": "myGalleryName",
            "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/galleries/myGalleryName",
            "location": "West US",
            "properties": {
              "description": "This is the gallery description.",
              "identifier": {
                "uniqueName": "{subscription-id}-MYGALLERYNAME"
              },
              "provisioningState": "Succeeded"
            }
          }
        ]
      }
    }
  },
  "operationId": "Galleries_ListByResourceGroup",
  "title": "List galleries in a resource group."
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/VirtualMachineScaleSetExtensions_List_VirtualMachineScaleSetExtensionListMinimumSetGen.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "resourceGroupName": "rgcompute",
    "subscriptionId": "{subscription-id}",
    "vmScaleSetName": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "responses": {
    "200": {
      "body": {
        "value": [
          {}
        ]
      }
    }
  },
  "operationId": "VirtualMachineScaleSetExtensions_List",
  "title": "VirtualMachineScaleSetExtension_List_MinimumSet_Gen"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/VirtualMachines_CreateOrUpdate_CreateAVmWithUefiSettingsOfSecureBootAndVTpm.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "parameters": {
      "location": "westus",
      "properties": {
        "hardwareProfile": {
          "vmSize": "Standard_D2s_v3"
        },
        "networkProfile": {
          "networkInterfaces": [
            {
              "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Network/networkInterfaces/{existing-nic-name}",
              "properties": {
                "primary": true
              }
            }
          ]
        },
        "osProfile": {
          "adminPassword": "{your-password}",
          "adminUsername": "{your-username}",
          "computerName": "myVM"
        },
        "securityProfile": {
          "securityType": "TrustedLaunch",
          "uefiSettings": {
            "secureBootEnabled": true,
            "vTpmEnabled": true
          }
        },
        "storageProfile": {
          "imageReference": {
            "offer": "windowsserver-gen2preview-preview",
            "publisher": "MicrosoftWindowsServer",
            "sku": "windows10-tvm",
            "version": "18363.592.2001092016"
          },
          "osDisk": {
            "name": "myVMosdisk",
            "caching": "ReadOnly",
            "createOption": "FromImage",
            "managedDisk": {
              "storageAccountType": "StandardSSD_LRS"
            }
          }
        }
      }
    },
    "resourceGroupName": "myResourceGroup",
    "subscriptionId": "{subscription-id}",
    "vmName": "myVM"
  },
  "responses": {
    "200": {
      "body": {
        "name": "myVM",
        "type": "Microsoft.Compute/virtualMachines",
        "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM",
        "location": "westus",
        "properties": {
          "hardwareProfile": {
            "vmSize": "Standard_D2s_v3"
          },
          "networkProfile": {
            "networkInterfaces": [
              {
                "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Network/networkInterfaces/nsgExistingNic",
                "properties": {
                  "primary": true
                }
              }
            ]
          },
          "osProfile": {
            "adminUsername": "{your-username}",
            "computerName": "myVM",
            "secrets": [],
            "windowsConfiguration": {
              "enableAutomaticUpdates": true,
              "provisionVMAgent": true
            }
          },
          "provisioningState": "Creating",
          "securityProfile": {
            "securityType": "TrustedLaunch",
            "uefiSettings": {
              "secureBootEnabled": true,
              "vTpmEnabled": true
            }
          },
          "storageProfile": {
            "dataDisks": [],
            "imageReference": {
              "offer": "windowsserver-gen2preview-preview",
              "publisher": "MicrosoftWindowsServer",
              "sku": "windows10-tvm",
              "version": "18363.592.2001092016"
            },
            "osDisk": {
              "name": "myVMosdisk",
              "caching": "ReadOnly",
              "createOption": "FromImage",
              "managedDisk": {
                "storageAccountType": "StandardSSD_LRS"
              },
              "osType": "Windows"
            }
          },
          "vmId": "5c0d55a7-c407-4ed6-bf7d-ddb810267c85"
        }
      }
    },
    "201": {
      "body": {
        "name": "myVM",
        "type": "Microsoft.Compute/virtualMachines",
        "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM",
        "location": "westus",
        "properties": {
          "hardwareProfile": {
            "vmSize": "Standard_D2s_v3"
          },
          "networkProfile": {
            "networkInterfaces": [
              {
                "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Network/networkInterfaces/nsgExistingNic",
                "properties": {
                  "primary": true
                }
              }
            ]
          },
          "osProfile": {
            "adminUsername": "{your-username}",
            "computerName": "myVM",
            "secrets": [],
            "windowsConfiguration": {
              "enableAutomaticUpdates": true,
              "provisionVMAgent": true
            }
          },
          "provisioningState": "Creating",
          "securityProfile": {
            "securityType": "TrustedLaunch",
            "uefiSettings": {
              "secureBootEnabled": true,
              "vTpmEnabled": true
            }
          },
          "storageProfile": {
            "dataDisks": [],
            "imageReference": {
              "offer": "windowsserver-gen2preview-preview",
              "publisher": "MicrosoftWindowsServer",
              "sku": "windows10-tvm",
              "version": "18363.592.2001092016"
            },
            "osDisk": {
              "name": "myVMosdisk",
              "caching": "ReadOnly",
              "createOption": "FromImage",
              "managedDisk": {
                "storageAccountType": "StandardSSD_LRS"
              },
              "osType": "Windows"
            }
          },
          "vmId": "5c0d55a7-c407-4ed6-bf7d-ddb810267c85"
        }
      }
    }
  },
  "operationId": "VirtualMachines_CreateOrUpdate",
  "title": "Create a VM with Uefi Settings of secureBoot and vTPM."
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/virtualMachineExamples/VirtualMachine_Deallocate_MaximumSet_Gen.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "hibernate": true,
    "resourceGroupName": "rgcompute",
    "subscriptionId": "{subscription-id}",
    "vmName": "aaaaaaaaaa"
  },
  "responses": {
    "200": {},
    "202": {
      "headers": {
        "location": "https://foo.com/operationstatus"
      }
    }
  },
  "operationId": "VirtualMachines_Deallocate",
  "title": "VirtualMachine_Deallocate_MaximumSet_Gen"
}

=== Azure/autorest/packages/extensions/openapi-to-typespec/test/arm-compute/tsp-output/examples/2023-07-01/VirtualMachineRunCommands_GetByVirtualMachine.json
{
  "parameters": {
    "api-version": "2023-07-01",
    "resourceGroupName": "myResourceGroup",
    "runCommandName": "myRunCommand",
    "subscriptionId": "{subscription-id}",
    "vmName": "myVM"
  },
  "responses": {
    "200": {
      "body": {
        "name": "myRunCommand",
        "type": "Microsoft.Compute/virtualMachines/runCommands",
        "id": "/subscriptions/{subscription-id}/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/myVM/runCommands/myRunCommand",
        "location": "westus",
        "properties": {
          "asyncExecution": false,
          "errorBlobUri": "https://mystorageaccount.blob.core.windows.net/mycontainer/MyScriptError.txt",
          "outputBlobUri": "https://mystorageaccount.blob.core.windows.net/myscriptoutputcontainer/MyScriptoutput.txt",
          "parameters": [
            {
              "name": "param1",
              "value": "value1"
            },
            {
              "name": "param2",
              "value": "value2"
            }
          ],
          "provisioningState": "Succeeded",
          "runAsUser": "user1",
          "source": {
            "script": "Write-Host Hello World! ; Remove-Item C:\test\testFile.txt"
          },
          "timeoutInSeconds": 3600,
          "treatFailureAsDeploymentFailure": false
        },
        "tags": {
          "tag1": "value1",
          "tag2": "value2"
        }
      }
    }
  },
  "operationId": "VirtualMachineRunCommands_GetByVirtualMachine",
  "title": "Get a run command."
}
